In [1]:
#Try and recreate EPL standings based on results for the 2020-2021 season
#EPL stands for English Premier League and is the top-flight professional soccer league played in England

import pandas as pd

df = pd.read_csv('C:Desktop/Datasets/EPL2122season.csv')

df.head()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,12/9/2020,12:30,Fulham,Arsenal,0,3,A,0,1,...,1.84,0.75,2.01,1.89,2.02,1.91,2.13,1.92,2.02,1.87
1,E0,12/9/2020,15:00,Crystal Palace,Southampton,1,0,H,1,0,...,1.70,0.25,1.78,2.13,1.79,2.17,1.85,2.18,1.79,2.12
2,E0,12/9/2020,17:30,Liverpool,Leeds,4,3,H,3,2,...,2.62,-1.50,1.85,2.05,1.85,2.08,1.90,2.16,1.84,2.04
3,E0,12/9/2020,20:00,West Ham,Newcastle,0,2,A,0,0,...,1.92,-0.50,2.03,1.87,2.04,1.88,2.09,1.91,2.02,1.86
4,E0,13/09/2020,14:00,West Brom,Leicester,0,3,A,0,0,...,1.73,0.25,1.92,1.98,1.93,1.99,1.95,2.01,1.91,1.97

In [2]:
#Renaming columns

df = df.rename(columns={
    'FTHG': 'HG',
    'FTAG': 'AG',
    'FTR': 'Winner'
})

df.head()

,Div,Date,Time,HomeTeam,AwayTeam,HG,AG,Winner,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,12/9/2020,12:30,Fulham,Arsenal,0,3,A,0,1,...,1.84,0.75,2.01,1.89,2.02,1.91,2.13,1.92,2.02,1.87
1,E0,12/9/2020,15:00,Crystal Palace,Southampton,1,0,H,1,0,...,1.70,0.25,1.78,2.13,1.79,2.17,1.85,2.18,1.79,2.12
2,E0,12/9/2020,17:30,Liverpool,Leeds,4,3,H,3,2,...,2.62,-1.50,1.85,2.05,1.85,2.08,1.90,2.16,1.84,2.04
3,E0,12/9/2020,20:00,West Ham,Newcastle,0,2,A,0,0,...,1.92,-0.50,2.03,1.87,2.04,1.88,2.09,1.91,2.02,1.86
4,E0,13/09/2020,14:00,West Brom,Leicester,0,3,A,0,0,...,1.73,0.25,1.92,1.98,1.93,1.99,1.95,2.01,1.91,1.97

In [3]:
#Pull list of columns to easily copy/paste into drop

list(df.columns.values.tolist())

['Div',
 'Date',
 'Time',
 'HomeTeam',
 'AwayTeam',
 'HG',
 'AG',
 'Winner',
 'HTHG',
 'HTAG',
 'HTR',
 'Referee',
 'HS',
 'AS',
 'HST',
 'AST',
 'HF',
 'AF',
 'HC',
 'AC',
 'HY',
 'AY',
 'HR',
 'AR',
 'B365H',
 'B365D',
 'B365A',
 'BWH',
 'BWD',
 'BWA',
 'IWH',
 'IWD',
 'IWA',
 'PSH',
 'PSD',
 'PSA',
 'WHH',
 'WHD',
 'WHA',
 'VCH',
 'VCD',
 'VCA',
 'MaxH',
 'MaxD',
 'MaxA',
 'AvgH',
 'AvgD',
 'AvgA',
 'B365>2.5',
 'B365<2.5',
 'P>2.5',
 'P<2.5',
 'Max>2.5',
 'Max<2.5',
 'Avg>2.5',
 'Avg<2.5',
 'AHh',
 'B365AHH',
 'B365AHA',
 'PAHH',
 'PAHA',
 'MaxAHH',
 'MaxAHA',
 'AvgAHH',
 'AvgAHA',
 'B365CH',
 'B365CD',
 'B365CA',
 'BWCH',
 'BWCD',
 'BWCA',
 'IWCH',
 'IWCD',
 'IWCA',
 'PSCH',
 'PSCD',
 'PSCA',
 'WHCH',
 'WHCD',
 'WHCA',
 'VCCH',
 'VCCD',
 'VCCA',
 'MaxCH',
 'MaxCD',
 'MaxCA',
 'AvgCH',
 'AvgCD',
 'AvgCA',
 'B365C>2.5',
 'B365C<2.5',
 'PC>2.5',
 'PC<2.5',
 'MaxC>2.5',
 'MaxC<2.5',
 'AvgC>2.5',
 'AvgC<2.5',
 'AHCh',
 'B365CAHH',
 'B365CAHA',
 'PCAHH',
 'PCAHA',
 'MaxCAHH',
 'MaxCAHA',
 'AvgCAHH',
 'AvgCAHA']

In [4]:
df.drop(['Div', 'HTHG', 'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC', 'HY', 'AY', 'HR', 'AR', 
         'B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'IWH', 'IWD', 'IWA', 'PSH', 'PSD', 'PSA', 'WHH', 'WHD', 'WHA', 'VCH',
         'VCD', 'VCA', 'MaxH', 'MaxD', 'MaxA', 'AvgH', 'AvgD', 'AvgA', 'B365>2.5', 'B365<2.5', 'P>2.5', 'P<2.5', 'Max>2.5',
         'Max<2.5', 'Avg>2.5', 'Avg<2.5', 'AHh', 'B365AHH', 'B365AHA', 'PAHH', 'PAHA', 'MaxAHH', 'MaxAHA', 'AvgAHH', 'AvgAHA',
         'B365CH', 'B365CD', 'B365CA', 'BWCH', 'BWCD', 'BWCA', 'IWCH', 'IWCD', 'IWCA', 'PSCH', 'PSCD', 'PSCA', 'WHCH', 'WHCD',
         'WHCA', 'VCCH', 'VCCD', 'VCCA', 'MaxCH', 'MaxCD', 'MaxCA', 'AvgCH', 'AvgCD', 'AvgCA', 'B365C>2.5', 'B365C<2.5',
         'PC>2.5', 'PC<2.5', 'MaxC>2.5', 'MaxC<2.5', 'AvgC>2.5', 'AvgC<2.5', 'AHCh', 'B365CAHH', 'B365CAHA', 'PCAHH', 'PCAHA',
         'MaxCAHH', 'MaxCAHA', 'AvgCAHH', 'AvgCAHA', 'Time'], axis=1, inplace=True)


df.head()

         Date        HomeTeam     AwayTeam  HG  AG Winner
0   12/9/2020          Fulham      Arsenal   0   3      A
1   12/9/2020  Crystal Palace  Southampton   1   0      H
2   12/9/2020       Liverpool        Leeds   4   3      H
3   12/9/2020        West Ham    Newcastle   0   2      A
4  13/09/2020       West Brom    Leicester   0   3      A

In [5]:
#Change date column to string format I want

df['Date'] = pd.to_datetime(df['Date'], dayfirst=True).dt.strftime('%m-%d-%Y')

df

           Date          HomeTeam          AwayTeam  HG  AG Winner
0    09-12-2020            Fulham           Arsenal   0   3      A
1    09-12-2020    Crystal Palace       Southampton   1   0      H
2    09-12-2020         Liverpool             Leeds   4   3      H
3    09-12-2020          West Ham         Newcastle   0   2      A
4    09-13-2020         West Brom         Leicester   0   3      A
5    09-13-2020         Tottenham           Everton   0   1      A
6    09-14-2020          Brighton           Chelsea   1   3      A
7    09-14-2020  Sheffield United            Wolves   0   2      A
8    09-19-2020           Everton         West Brom   5   2      H
9    09-19-2020             Leeds            Fulham   4   3      H
10   09-19-2020        Man United    Crystal Palace   1   3      A
11   09-19-2020           Arsenal          West Ham   2   1      H
12   09-20-2020       Southampton         Tottenham   2   5      A
13   09-20-2020         Newcastle          Brighton   0   3      A
14   09-20-2020           Chelsea         Liverpool   0   2      A
15   09-20-2020         Leicester           Burnley   4   2      H
16   09-21-2020       Aston Villa  Sheffield United   1   0      H
17   09-21-2020            Wolves          Man City   1   3      A
18   09-26-2020          Brighton        Man United   2   3      A
19   09-26-2020    Crystal Palace           Everton   1   2      A
20   09-26-2020         West Brom           Chelsea   3   3      D
21   09-26-2020           Burnley       Southampton   0   1      A
22   09-27-2020  Sheffield United             Leeds   0   1      A
23   09-27-2020         Tottenham         Newcastle   1   1      D
24   09-27-2020          Man City         Leicester   2   5      A
25   09-27-2020          West Ham            Wolves   4   0      H
26   09-28-2020            Fulham       Aston Villa   0   3      A
27   09-28-2020         Liverpool           Arsenal   3   1      H
28   10-03-2020           Chelsea    Crystal Palace   4   0      H
29   10-03-2020           Everton          Brighton   4   2      H
..          ...               ...               ...  ..  ..    ...
350  05-13-2021       Aston Villa           Everton   0   0      D
351  05-13-2021        Man United         Liverpool   2   4      A
352  05-14-2021         Newcastle          Man City   3   4      A
353  05-15-2021           Burnley             Leeds   0   4      A
354  05-15-2021       Southampton            Fulham   3   1      H
355  05-15-2021          Brighton          West Ham   1   1      D
356  05-16-2021    Crystal Palace       Aston Villa   3   2      H
357  05-16-2021         Tottenham            Wolves   2   0      H
358  05-16-2021         West Brom         Liverpool   1   2      A
359  05-16-2021           Everton  Sheffield United   0   1      A
360  05-18-2021        Man United            Fulham   1   1      D
361  05-18-2021       Southampton             Leeds   0   2      A
362  05-18-2021          Brighton          Man City   3   2      H
363  05-18-2021           Chelsea         Leicester   2   1      H
364  05-19-2021           Everton            Wolves   1   0      H
365  05-19-2021         Newcastle  Sheffield United   1   0      H
366  05-19-2021         Tottenham       Aston Villa   1   2      A
367  05-19-2021    Crystal Palace           Arsenal   1   3      A
368  05-19-2021           Burnley         Liverpool   0   3      A
369  05-19-2021         West Brom          West Ham   1   3      A
370  05-23-2021           Arsenal          Brighton   2   0      H
371  05-23-2021       Aston Villa           Chelsea   2   1      H
372  05-23-2021            Fulham         Newcastle   0   2      A
373  05-23-2021             Leeds         West Brom   3   1      H
374  05-23-2021         Leicester         Tottenham   2   4      A
375  05-23-2021         Liverpool    Crystal Palace   2   0      H
376  05-23-2021          Man City           Everton   5   0      H
377  05-23-2021  Sheffield United           Burnley   1   0      H
378  05-23-2021          West Ham       Southampton   3   0      H
379  05-23-2021            Wolves        Man United   1   2      A

[380 rows x 6 columns]

In [6]:
#See all unique teams to check I have 20

df['HomeTeam'].unique()

array(['Fulham', 'Crystal Palace', 'Liverpool', 'West Ham', 'West Brom',
       'Tottenham', 'Brighton', 'Sheffield United', 'Everton', 'Leeds',
       'Man United', 'Arsenal', 'Southampton', 'Newcastle', 'Chelsea',
       'Leicester', 'Aston Villa', 'Wolves', 'Burnley', 'Man City'],
      dtype=object)

In [49]:
# Create first dataframe for the team I want to start with

df_tottenham = df.loc[(df['HomeTeam'] == 'Tottenham') | (df['AwayTeam'] == 'Tottenham')]


df_tottenham.head()

          Date     HomeTeam   AwayTeam  HG  AG Winner
5   09-13-2020    Tottenham    Everton   0   1      A
12  09-20-2020  Southampton  Tottenham   2   5      A
23  09-27-2020    Tottenham  Newcastle   1   1      D
36  10-04-2020   Man United  Tottenham   1   6      A
44  10-18-2020    Tottenham   West Ham   3   3      D

In [8]:
# In soccer, it is 3 points for a win, 1 point for a draw, and 0 points for a loss
# For each team dataframe, I'll need to write some logic to gather and add all the points up

df_tottenham.loc[(df_tottenham['HomeTeam'] == 'Tottenham') & 
                 (df_tottenham['Winner'] == 'H'), 'Points'] = 3
df_tottenham.loc[(df_tottenham['AwayTeam'] == 'Tottenham') & 
                 (df_tottenham['Winner'] == 'A'), 'Points'] = 3
df_tottenham.loc[(df_tottenham['HomeTeam'] == 'Tottenham') & 
                 (df_tottenham['Winner'] == 'A'), 'Points'] = 0
df_tottenham.loc[(df_tottenham['AwayTeam'] == 'Tottenham') & 
                 (df_tottenham['Winner'] == 'H'), 'Points'] = 0
df_tottenham.loc[(df_tottenham['HomeTeam'] == 'Tottenham') & 
                 (df_tottenham['Winner'] == 'D'), 'Points'] = 1
df_tottenham.loc[(df_tottenham['AwayTeam'] == 'Tottenham') & 
                 (df_tottenham['Winner'] == 'D'), 'Points'] = 1

df_tottenham

C:\Users\tjame\Anaconda3\lib\site-packages\pandas\core\indexing.py:362: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[key] = _infer_fill_value(value)
C:\Users\tjame\Anaconda3\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

           Date          HomeTeam          AwayTeam  HG  AG Winner  Points
5    09-13-2020         Tottenham           Everton   0   1      A     0.0
12   09-20-2020       Southampton         Tottenham   2   5      A     3.0
23   09-27-2020         Tottenham         Newcastle   1   1      D     1.0
36   10-04-2020        Man United         Tottenham   1   6      A     3.0
44   10-18-2020         Tottenham          West Ham   3   3      D     1.0
57   10-26-2020           Burnley         Tottenham   0   1      A     3.0
65   11-01-2020         Tottenham          Brighton   2   1      H     3.0
74   11-08-2020         West Brom         Tottenham   0   1      A     3.0
80   11-21-2020         Tottenham          Man City   2   0      H     3.0
94   11-29-2020           Chelsea         Tottenham   0   0      D     1.0
104  12-06-2020         Tottenham           Arsenal   2   0      H     3.0
113  12-13-2020    Crystal Palace         Tottenham   1   1      D     1.0
123  12-16-2020         Liverpool         Tottenham   2   1      H     0.0
132  12-20-2020         Tottenham         Leicester   0   2      A     0.0
146  12-27-2020            Wolves         Tottenham   1   1      D     1.0
157  01-02-2021         Tottenham             Leeds   3   0      H     3.0
168  01-13-2021         Tottenham            Fulham   1   1      D     1.0
175  01-17-2021  Sheffield United         Tottenham   1   3      A     3.0
194  01-28-2021         Tottenham         Liverpool   1   3      A     0.0
204  01-31-2021          Brighton         Tottenham   1   0      H     0.0
214  02-04-2021         Tottenham           Chelsea   0   1      A     0.0
220  02-07-2021         Tottenham         West Brom   2   0      H     3.0
227  02-13-2021          Man City         Tottenham   3   0      H     0.0
242  02-21-2021          West Ham         Tottenham   2   1      H     0.0
254  02-28-2021         Tottenham           Burnley   4   0      H     3.0
262  03-04-2021            Fulham         Tottenham   0   1      A     3.0
272  03-07-2021         Tottenham    Crystal Palace   4   1      H     3.0
283  03-14-2021           Arsenal         Tottenham   2   1      H     0.0
289  03-21-2021       Aston Villa         Tottenham   0   2      A     3.0
295  04-04-2021         Newcastle         Tottenham   2   2      D     1.0
306  04-11-2021         Tottenham        Man United   1   3      A     0.0
310  04-16-2021           Everton         Tottenham   2   2      D     1.0
317  04-21-2021         Tottenham       Southampton   2   1      H     3.0
334  05-02-2021         Tottenham  Sheffield United   4   0      H     3.0
338  05-08-2021             Leeds         Tottenham   3   1      H     0.0
357  05-16-2021         Tottenham            Wolves   2   0      H     3.0
366  05-19-2021         Tottenham       Aston Villa   1   2      A     0.0
374  05-23-2021         Leicester         Tottenham   2   4      A     3.0

In [9]:
# Let's sum up all of Tottenham's points for the season

tottenhampoints = df_tottenham['Points'].sum()
tottenhampoints

62.0

In [10]:
# Now we can create a dataframe for each team in the league
# Then we will create points logic for each database

df_mancity = df.loc[(df['HomeTeam'] == 'Man City') | (df['AwayTeam'] == 'Man City')]
df_fulham = df.loc[(df['HomeTeam'] == 'Fulham') | (df['AwayTeam'] == 'Fulham')]
df_cp = df.loc[(df['HomeTeam'] == 'Crystal Palace') | (df['AwayTeam'] == 'Crystal Palace')]
df_liverpool = df.loc[(df['HomeTeam'] == 'Liverpool') | (df['AwayTeam'] == 'Liverpool')]
df_wh = df.loc[(df['HomeTeam'] == 'West Ham') | (df['AwayTeam'] == 'West Ham')]
df_wb = df.loc[(df['HomeTeam'] == 'West Brom') | (df['AwayTeam'] == 'West Brom')]
df_brighton = df.loc[(df['HomeTeam'] == 'Brighton') | (df['AwayTeam'] == 'Brighton')]
df_sheffield = df.loc[(df['HomeTeam'] == 'Sheffield United') | (df['AwayTeam'] == 'Sheffield United')]
df_everton = df.loc[(df['HomeTeam'] == 'Everton') | (df['AwayTeam'] == 'Everton')]
df_leeds = df.loc[(df['HomeTeam'] == 'Leeds') | (df['AwayTeam'] == 'Leeds')]
df_manu = df.loc[(df['HomeTeam'] == 'Man United') | (df['AwayTeam'] == 'Man United')]
df_arsenal = df.loc[(df['HomeTeam'] == 'Arsenal') | (df['AwayTeam'] == 'Arsenal')]
df_soton = df.loc[(df['HomeTeam'] == 'Southampton') | (df['AwayTeam'] == 'Southampton')]
df_newcastle = df.loc[(df['HomeTeam'] == 'Newcastle') | (df['AwayTeam'] == 'Newcastle')]
df_chelsea = df.loc[(df['HomeTeam'] == 'Chelsea') | (df['AwayTeam'] == 'Chelsea')]
df_leicester = df.loc[(df['HomeTeam'] == 'Leicester') | (df['AwayTeam'] == 'Leicester')]
df_av = df.loc[(df['HomeTeam'] == 'Aston Villa') | (df['AwayTeam'] == 'Aston Villa')]
df_wolves = df.loc[(df['HomeTeam'] == 'Wolves') | (df['AwayTeam'] == 'Wolves')]
df_burnley = df.loc[(df['HomeTeam'] == 'Burnley') | (df['AwayTeam'] == 'Burnley')]

In [11]:
df_mancity.loc[(df_mancity['HomeTeam'] == 'Man City') & 
               (df_mancity['Winner'] == 'H'), 'Points'] = 3
df_mancity.loc[(df_mancity['AwayTeam'] == 'Man City') & 
               (df_mancity['Winner'] == 'A'), 'Points'] = 3
df_mancity.loc[(df_mancity['HomeTeam'] == 'Man City') & 
               (df_mancity['Winner'] == 'A'), 'Points'] = 0
df_mancity.loc[(df_mancity['AwayTeam'] == 'Man City') & 
               (df_mancity['Winner'] == 'H'), 'Points'] = 0
df_mancity.loc[(df_mancity['HomeTeam'] == 'Man City') & 
               (df_mancity['Winner'] == 'D'), 'Points'] = 1
df_mancity.loc[(df_mancity['AwayTeam'] == 'Man City') & 
               (df_mancity['Winner'] == 'D'), 'Points'] = 1

df_mancity

           Date          HomeTeam          AwayTeam  HG  AG Winner  Points
17   09-21-2020            Wolves          Man City   1   3      A     3.0
24   09-27-2020          Man City         Leicester   2   5      A     0.0
30   10-03-2020             Leeds          Man City   1   1      D     1.0
40   10-17-2020          Man City           Arsenal   1   0      H     3.0
49   10-24-2020          West Ham          Man City   1   1      D     1.0
59   10-31-2020  Sheffield United          Man City   0   1      A     3.0
76   11-08-2020          Man City         Liverpool   1   1      D     1.0
80   11-21-2020         Tottenham          Man City   2   0      H     0.0
90   11-28-2020          Man City           Burnley   5   0      H     3.0
99   12-05-2020          Man City            Fulham   2   0      H     3.0
110  12-12-2020        Man United          Man City   0   0      D     1.0
118  12-15-2020          Man City         West Brom   1   1      D     1.0
128  12-19-2020       Southampton          Man City   0   1      A     3.0
141  12-26-2020          Man City         Newcastle   2   0      H     3.0
162  01-03-2021           Chelsea          Man City   1   3      A     3.0
167  01-13-2021          Man City          Brighton   1   0      H     3.0
177  01-17-2021          Man City    Crystal Palace   4   0      H     3.0
181  01-20-2021          Man City       Aston Villa   2   0      H     3.0
188  01-26-2021         West Brom          Man City   0   5      A     3.0
197  01-30-2021          Man City  Sheffield United   1   0      H     3.0
209  02-03-2021           Burnley          Man City   0   2      A     3.0
222  02-07-2021         Liverpool          Man City   1   4      A     3.0
227  02-13-2021          Man City         Tottenham   3   0      H     3.0
236  02-17-2021           Everton          Man City   1   3      A     3.0
244  02-21-2021           Arsenal          Man City   0   1      A     3.0
248  02-27-2021          Man City          West Ham   2   1      H     3.0
258  03-02-2021          Man City            Wolves   4   1      H     3.0
271  03-07-2021          Man City        Man United   0   2      A     0.0
275  03-10-2021          Man City       Southampton   5   2      H     3.0
280  03-13-2021            Fulham          Man City   0   3      A     3.0
292  04-03-2021         Leicester          Man City   0   2      A     3.0
301  04-10-2021          Man City             Leeds   1   2      A     0.0
318  04-21-2021       Aston Villa          Man City   1   2      A     3.0
329  05-01-2021    Crystal Palace          Man City   0   2      A     3.0
340  05-08-2021          Man City           Chelsea   1   2      A     0.0
352  05-14-2021         Newcastle          Man City   3   4      A     3.0
362  05-18-2021          Brighton          Man City   3   2      H     0.0
376  05-23-2021          Man City           Everton   5   0      H     3.0

In [12]:
mancitypoints = df_mancity['Points'].sum()
mancitypoints

86.0

In [13]:
df_fulham.loc[(df_fulham['HomeTeam'] == 'Fulham') & 
              (df_fulham['Winner'] == 'H'), 'Points'] = 3
df_fulham.loc[(df_fulham['AwayTeam'] == 'Fulham') & 
              (df_fulham['Winner'] == 'A'), 'Points'] = 3
df_fulham.loc[(df_fulham['HomeTeam'] == 'Fulham') & 
              (df_fulham['Winner'] == 'A'), 'Points'] = 0
df_fulham.loc[(df_fulham['AwayTeam'] == 'Fulham') & 
              (df_fulham['Winner'] == 'H'), 'Points'] = 0
df_fulham.loc[(df_fulham['HomeTeam'] == 'Fulham') & 
              (df_fulham['Winner'] == 'D'), 'Points'] = 1
df_fulham.loc[(df_fulham['AwayTeam'] == 'Fulham') & 
              (df_fulham['Winner'] == 'D'), 'Points'] = 1

fulhampoints = df_fulham['Points'].sum()

In [14]:
df_cp.loc[(df_cp['HomeTeam'] == 'Crystal Palace') & 
                 (df_cp['Winner'] == 'H'), 'Points'] = 3
df_cp.loc[(df_cp['AwayTeam'] == 'Crystal Palace') & 
                 (df_cp['Winner'] == 'A'), 'Points'] = 3
df_cp.loc[(df_cp['HomeTeam'] == 'Crystal Palace') & 
                 (df_cp['Winner'] == 'A'), 'Points'] = 0
df_cp.loc[(df_cp['AwayTeam'] == 'Crystal Palace') & 
                 (df_cp['Winner'] == 'H'), 'Points'] = 0
df_cp.loc[(df_cp['HomeTeam'] == 'Crystal Palace') & 
                 (df_cp['Winner'] == 'D'), 'Points'] = 1
df_cp.loc[(df_cp['AwayTeam'] == 'Crystal Palace') & 
                 (df_cp['Winner'] == 'D'), 'Points'] = 1
    
cppoints = df_cp['Points'].sum()

In [15]:
df_liverpool.loc[(df_liverpool['HomeTeam'] == 'Liverpool') & 
                 (df_liverpool['Winner'] == 'H'), 'Points'] = 3
df_liverpool.loc[(df_liverpool['AwayTeam'] == 'Liverpool') & 
                 (df_liverpool['Winner'] == 'A'), 'Points'] = 3
df_liverpool.loc[(df_liverpool['HomeTeam'] == 'Liverpool') & 
                 (df_liverpool['Winner'] == 'A'), 'Points'] = 0
df_liverpool.loc[(df_liverpool['AwayTeam'] == 'Liverpool') & 
                 (df_liverpool['Winner'] == 'H'), 'Points'] = 0
df_liverpool.loc[(df_liverpool['HomeTeam'] == 'Liverpool') & 
                 (df_liverpool['Winner'] == 'D'), 'Points'] = 1
df_liverpool.loc[(df_liverpool['AwayTeam'] == 'Liverpool') & 
                 (df_liverpool['Winner'] == 'D'), 'Points'] = 1

liverpoolpoints = df_liverpool['Points'].sum()

In [16]:
df_wh.loc[(df_wh['HomeTeam'] == 'West Ham') & 
                 (df_wh['Winner'] == 'H'), 'Points'] = 3
df_wh.loc[(df_wh['AwayTeam'] == 'West Ham') & 
                 (df_wh['Winner'] == 'A'), 'Points'] = 3
df_wh.loc[(df_wh['HomeTeam'] == 'West Ham') & 
                 (df_wh['Winner'] == 'A'), 'Points'] = 0
df_wh.loc[(df_wh['AwayTeam'] == 'West Ham') & 
                 (df_wh['Winner'] == 'H'), 'Points'] = 0
df_wh.loc[(df_wh['HomeTeam'] == 'West Ham') & 
                 (df_wh['Winner'] == 'D'), 'Points'] = 1
df_wh.loc[(df_wh['AwayTeam'] == 'West Ham') & 
                 (df_wh['Winner'] == 'D'), 'Points'] = 1

whpoints = df_wh['Points'].sum()

In [17]:
df_wb.loc[(df_wb['HomeTeam'] == 'West Brom') & 
                 (df_wb['Winner'] == 'H'), 'Points'] = 3
df_wb.loc[(df_wb['AwayTeam'] == 'West Brom') & 
                 (df_wb['Winner'] == 'A'), 'Points'] = 3
df_wb.loc[(df_wb['HomeTeam'] == 'West Brom') & 
                 (df_wb['Winner'] == 'A'), 'Points'] = 0
df_wb.loc[(df_wb['AwayTeam'] == 'West Brom') & 
                 (df_wb['Winner'] == 'H'), 'Points'] = 0
df_wb.loc[(df_wb['HomeTeam'] == 'West Brom') & 
                 (df_wb['Winner'] == 'D'), 'Points'] = 1
df_wb.loc[(df_wb['AwayTeam'] == 'West Brom') & 
                 (df_wb['Winner'] == 'D'), 'Points'] = 1

wbpoints = df_wb['Points'].sum()

In [18]:
df_brighton.loc[(df_brighton['HomeTeam'] == 'Brighton') & 
                 (df_brighton['Winner'] == 'H'), 'Points'] = 3
df_brighton.loc[(df_brighton['AwayTeam'] == 'Brighton') & 
                 (df_brighton['Winner'] == 'A'), 'Points'] = 3
df_brighton.loc[(df_brighton['HomeTeam'] == 'Brighton') & 
                 (df_brighton['Winner'] == 'A'), 'Points'] = 0
df_brighton.loc[(df_brighton['AwayTeam'] == 'Brighton') & 
                 (df_brighton['Winner'] == 'H'), 'Points'] = 0
df_brighton.loc[(df_brighton['HomeTeam'] == 'Brighton') & 
                 (df_brighton['Winner'] == 'D'), 'Points'] = 1
df_brighton.loc[(df_brighton['AwayTeam'] == 'Brighton') & 
                 (df_brighton['Winner'] == 'D'), 'Points'] = 1
    
brightonpoints = df_brighton['Points'].sum()

In [19]:
df_sheffield.loc[(df_sheffield['HomeTeam'] == 'Sheffield United') & 
                 (df_sheffield['Winner'] == 'H'), 'Points'] = 3
df_sheffield.loc[(df_sheffield['AwayTeam'] == 'Sheffield United') & 
                 (df_sheffield['Winner'] == 'A'), 'Points'] = 3
df_sheffield.loc[(df_sheffield['HomeTeam'] == 'Sheffield United') & 
                 (df_sheffield['Winner'] == 'A'), 'Points'] = 0
df_sheffield.loc[(df_sheffield['AwayTeam'] == 'Sheffield United') & 
                 (df_sheffield['Winner'] == 'H'), 'Points'] = 0
df_sheffield.loc[(df_sheffield['HomeTeam'] == 'Sheffield United') & 
                 (df_sheffield['Winner'] == 'D'), 'Points'] = 1
df_sheffield.loc[(df_sheffield['AwayTeam'] == 'Sheffield United') & 
                 (df_sheffield['Winner'] == 'D'), 'Points'] = 1
    
sheffieldpoints = df_sheffield['Points'].sum()

In [20]:
df_everton.loc[(df_everton['HomeTeam'] == 'Everton') & 
                 (df_everton['Winner'] == 'H'), 'Points'] = 3
df_everton.loc[(df_everton['AwayTeam'] == 'Everton') & 
                 (df_everton['Winner'] == 'A'), 'Points'] = 3
df_everton.loc[(df_everton['HomeTeam'] == 'Everton') & 
                 (df_everton['Winner'] == 'A'), 'Points'] = 0
df_everton.loc[(df_everton['AwayTeam'] == 'Everton') & 
                 (df_everton['Winner'] == 'H'), 'Points'] = 0
df_everton.loc[(df_everton['HomeTeam'] == 'Everton') & 
                 (df_everton['Winner'] == 'D'), 'Points'] = 1
df_everton.loc[(df_everton['AwayTeam'] == 'Everton') & 
                 (df_everton['Winner'] == 'D'), 'Points'] = 1
    
evertonpoints = df_everton['Points'].sum()

In [21]:
df_leeds.loc[(df_leeds['HomeTeam'] == 'Leeds') & 
             (df_leeds['Winner'] == 'H'), 'Points'] = 3
df_leeds.loc[(df_leeds['AwayTeam'] == 'Leeds') & 
             (df_leeds['Winner'] == 'A'), 'Points'] = 3
df_leeds.loc[(df_leeds['HomeTeam'] == 'Leeds') & 
             (df_leeds['Winner'] == 'A'), 'Points'] = 0
df_leeds.loc[(df_leeds['AwayTeam'] == 'Leeds') & 
             (df_leeds['Winner'] == 'H'), 'Points'] = 0
df_leeds.loc[(df_leeds['HomeTeam'] == 'Leeds') & 
             (df_leeds['Winner'] == 'D'), 'Points'] = 1
df_leeds.loc[(df_leeds['AwayTeam'] == 'Leeds') & 
             (df_leeds['Winner'] == 'D'), 'Points'] = 1
    
leedspoints = df_leeds['Points'].sum()

In [22]:
df_manu.loc[(df_manu['HomeTeam'] == 'Man United') & 
             (df_manu['Winner'] == 'H'), 'Points'] = 3
df_manu.loc[(df_manu['AwayTeam'] == 'Man United') & 
             (df_manu['Winner'] == 'A'), 'Points'] = 3
df_manu.loc[(df_manu['HomeTeam'] == 'Man United') & 
             (df_manu['Winner'] == 'A'), 'Points'] = 0
df_manu.loc[(df_manu['AwayTeam'] == 'Man United') & 
             (df_manu['Winner'] == 'H'), 'Points'] = 0
df_manu.loc[(df_manu['HomeTeam'] == 'Man United') & 
             (df_manu['Winner'] == 'D'), 'Points'] = 1
df_manu.loc[(df_manu['AwayTeam'] == 'Man United') & 
             (df_manu['Winner'] == 'D'), 'Points'] = 1
    
manupoints = df_manu['Points'].sum()

In [23]:
df_arsenal.loc[(df_arsenal['HomeTeam'] == 'Arsenal') & 
             (df_arsenal['Winner'] == 'H'), 'Points'] = 3
df_arsenal.loc[(df_arsenal['AwayTeam'] == 'Arsenal') & 
             (df_arsenal['Winner'] == 'A'), 'Points'] = 3
df_arsenal.loc[(df_arsenal['HomeTeam'] == 'Arsenal') & 
             (df_arsenal['Winner'] == 'A'), 'Points'] = 0
df_arsenal.loc[(df_arsenal['AwayTeam'] == 'Arsenal') & 
             (df_arsenal['Winner'] == 'H'), 'Points'] = 0
df_arsenal.loc[(df_arsenal['HomeTeam'] == 'Arsenal') & 
             (df_arsenal['Winner'] == 'D'), 'Points'] = 1
df_arsenal.loc[(df_arsenal['AwayTeam'] == 'Arsenal') & 
             (df_arsenal['Winner'] == 'D'), 'Points'] = 1
    
arsenalpoints = df_arsenal['Points'].sum()

In [24]:
df_soton.loc[(df_soton['HomeTeam'] == 'Southampton') & 
             (df_soton['Winner'] == 'H'), 'Points'] = 3
df_soton.loc[(df_soton['AwayTeam'] == 'Southampton') & 
             (df_soton['Winner'] == 'A'), 'Points'] = 3
df_soton.loc[(df_soton['HomeTeam'] == 'Southampton') & 
             (df_soton['Winner'] == 'A'), 'Points'] = 0
df_soton.loc[(df_soton['AwayTeam'] == 'Southampton') & 
             (df_soton['Winner'] == 'H'), 'Points'] = 0
df_soton.loc[(df_soton['HomeTeam'] == 'Southampton') & 
             (df_soton['Winner'] == 'D'), 'Points'] = 1
df_soton.loc[(df_soton['AwayTeam'] == 'Southampton') & 
             (df_soton['Winner'] == 'D'), 'Points'] = 1
    
sotonpoints = df_soton['Points'].sum()

In [25]:
df_newcastle.loc[(df_newcastle['HomeTeam'] == 'Newcastle') & 
                 (df_newcastle['Winner'] == 'H'), 'Points'] = 3
df_newcastle.loc[(df_newcastle['AwayTeam'] == 'Newcastle') & 
                 (df_newcastle['Winner'] == 'A'), 'Points'] = 3
df_newcastle.loc[(df_newcastle['HomeTeam'] == 'Newcastle') & 
                 (df_newcastle['Winner'] == 'A'), 'Points'] = 0
df_newcastle.loc[(df_newcastle['AwayTeam'] == 'Newcastle') & 
                 (df_newcastle['Winner'] == 'H'), 'Points'] = 0
df_newcastle.loc[(df_newcastle['HomeTeam'] == 'Newcastle') & 
                 (df_newcastle['Winner'] == 'D'), 'Points'] = 1
df_newcastle.loc[(df_newcastle['AwayTeam'] == 'Newcastle') & 
                 (df_newcastle['Winner'] == 'D'), 'Points'] = 1
    
newcastlepoints = df_newcastle['Points'].sum()

In [26]:
df_chelsea.loc[(df_chelsea['HomeTeam'] == 'Chelsea') & 
               (df_chelsea['Winner'] == 'H'), 'Points'] = 3
df_chelsea.loc[(df_chelsea['AwayTeam'] == 'Chelsea') & 
               (df_chelsea['Winner'] == 'A'), 'Points'] = 3
df_chelsea.loc[(df_chelsea['HomeTeam'] == 'Chelsea') & 
               (df_chelsea['Winner'] == 'A'), 'Points'] = 0
df_chelsea.loc[(df_chelsea['AwayTeam'] == 'Chelsea') & 
               (df_chelsea['Winner'] == 'H'), 'Points'] = 0
df_chelsea.loc[(df_chelsea['HomeTeam'] == 'Chelsea') & 
               (df_chelsea['Winner'] == 'D'), 'Points'] = 1
df_chelsea.loc[(df_chelsea['AwayTeam'] == 'Chelsea') & 
               (df_chelsea['Winner'] == 'D'), 'Points'] = 1

chelseapoints = df_chelsea['Points'].sum()

In [27]:
df_leicester.loc[(df_leicester['HomeTeam'] == 'Leicester') & 
               (df_leicester['Winner'] == 'H'), 'Points'] = 3
df_leicester.loc[(df_leicester['AwayTeam'] == 'Leicester') & 
               (df_leicester['Winner'] == 'A'), 'Points'] = 3
df_leicester.loc[(df_leicester['HomeTeam'] == 'Leicester') & 
               (df_leicester['Winner'] == 'A'), 'Points'] = 0
df_leicester.loc[(df_leicester['AwayTeam'] == 'Leicester') & 
               (df_leicester['Winner'] == 'H'), 'Points'] = 0
df_leicester.loc[(df_leicester['HomeTeam'] == 'Leicester') & 
               (df_leicester['Winner'] == 'D'), 'Points'] = 1
df_leicester.loc[(df_leicester['AwayTeam'] == 'Leicester') & 
               (df_leicester['Winner'] == 'D'), 'Points'] = 1
    
leicesterpoints = df_leicester['Points'].sum()

In [28]:
df_av.loc[(df_av['HomeTeam'] == 'Aston Villa') & 
               (df_av['Winner'] == 'H'), 'Points'] = 3
df_av.loc[(df_av['AwayTeam'] == 'Aston Villa') & 
               (df_av['Winner'] == 'A'), 'Points'] = 3
df_av.loc[(df_av['HomeTeam'] == 'Aston Villa') & 
               (df_av['Winner'] == 'A'), 'Points'] = 0
df_av.loc[(df_av['AwayTeam'] == 'Aston Villa') & 
               (df_av['Winner'] == 'H'), 'Points'] = 0
df_av.loc[(df_av['HomeTeam'] == 'Aston Villa') & 
               (df_av['Winner'] == 'D'), 'Points'] = 1
df_av.loc[(df_av['AwayTeam'] == 'Aston Villa') & 
               (df_av['Winner'] == 'D'), 'Points'] = 1
    
avpoints = df_av['Points'].sum()

In [29]:
df_wolves.loc[(df_wolves['HomeTeam'] == 'Wolves') & 
               (df_wolves['Winner'] == 'H'), 'Points'] = 3
df_wolves.loc[(df_wolves['AwayTeam'] == 'Wolves') & 
               (df_wolves['Winner'] == 'A'), 'Points'] = 3
df_wolves.loc[(df_wolves['HomeTeam'] == 'Wolves') & 
               (df_wolves['Winner'] == 'A'), 'Points'] = 0
df_wolves.loc[(df_wolves['AwayTeam'] == 'Wolves') & 
               (df_wolves['Winner'] == 'H'), 'Points'] = 0
df_wolves.loc[(df_wolves['HomeTeam'] == 'Wolves') & 
               (df_wolves['Winner'] == 'D'), 'Points'] = 1
df_wolves.loc[(df_wolves['AwayTeam'] == 'Wolves') & 
               (df_wolves['Winner'] == 'D'), 'Points'] = 1
    
wolvespoints = df_wolves['Points'].sum()

In [30]:
df_burnley.loc[(df_burnley['HomeTeam'] == 'Burnley') & 
               (df_burnley['Winner'] == 'H'), 'Points'] = 3
df_burnley.loc[(df_burnley['AwayTeam'] == 'Burnley') & 
               (df_burnley['Winner'] == 'A'), 'Points'] = 3
df_burnley.loc[(df_burnley['HomeTeam'] == 'Burnley') & 
               (df_burnley['Winner'] == 'A'), 'Points'] = 0
df_burnley.loc[(df_burnley['AwayTeam'] == 'Burnley') & 
               (df_burnley['Winner'] == 'H'), 'Points'] = 0
df_burnley.loc[(df_burnley['HomeTeam'] == 'Burnley') & 
               (df_burnley['Winner'] == 'D'), 'Points'] = 1
df_burnley.loc[(df_burnley['AwayTeam'] == 'Burnley') & 
               (df_burnley['Winner'] == 'D'), 'Points'] = 1

burnleypoints = df_burnley['Points'].sum()

In [36]:
# Now that we have a complete dataframe for each team I want to combine them into the same dataframe to create our EPL Table

d = {'Teams': ['Fulham', 'Crystal Palace', 'Liverpool', 'West Ham', 'West Brom',
       'Tottenham', 'Brighton', 'Sheffield United', 'Everton', 'Leeds',
       'Man United', 'Arsenal', 'Southampton', 'Newcastle', 'Chelsea',
       'Leicester', 'Aston Villa', 'Wolves', 'Burnley', 'Man City'], 
     'Points': [fulhampoints, cppoints, liverpoolpoints, whpoints, wbpoints,
               tottenhampoints, brightonpoints, sheffieldpoints, evertonpoints, leedspoints,
               manupoints, arsenalpoints, sotonpoints, newcastlepoints, chelseapoints,
               leicesterpoints, avpoints, wolvespoints, burnleypoints, mancitypoints]}
df_epltable = pd.DataFrame(data=d)
df_epltable

               Teams  Points
0             Fulham    28.0
1     Crystal Palace    44.0
2          Liverpool    69.0
3           West Ham    65.0
4          West Brom    26.0
5          Tottenham    62.0
6           Brighton    41.0
7   Sheffield United    23.0
8            Everton    59.0
9              Leeds    59.0
10        Man United    74.0
11           Arsenal    61.0
12       Southampton    43.0
13         Newcastle    45.0
14           Chelsea    67.0
15         Leicester    66.0
16       Aston Villa    55.0
17            Wolves    45.0
18           Burnley    39.0
19          Man City    86.0

In [37]:
#Lastly need to sort by descending as the team with the most points wins the league
# Manchester City are your 2020-2021 EPL Champions!

df_epltable.sort_values(by=['Points'], ascending=False)

               Teams  Points
19          Man City    86.0
10        Man United    74.0
2          Liverpool    69.0
14           Chelsea    67.0
15         Leicester    66.0
3           West Ham    65.0
5          Tottenham    62.0
11           Arsenal    61.0
8            Everton    59.0
9              Leeds    59.0
16       Aston Villa    55.0
13         Newcastle    45.0
17            Wolves    45.0
1     Crystal Palace    44.0
12       Southampton    43.0
6           Brighton    41.0
18           Burnley    39.0
0             Fulham    28.0
4          West Brom    26.0
7   Sheffield United    23.0

In [ ]:
# Here is a link to the standings to check my work
# https://www.google.com/search?q=epl+table+2020-2021&rlz=1C1GCEA_enUS799US799&oq=epl+table+2020-2021&aqs=chrome..69i57j0i22i30l8j0i22i30i457.6000j0j7&sourceid=chrome&ie=UTF-8#sie=lg;/g/11j4y8fvpd;2;/m/02_tc;st;fp;1;;